[config]
default_to_workspace = false

[env]
RUSTC_BOOTSTRAP = 1
NO_STD_FLAGS = "--profile ${RUSTC_PROFILE} -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem -Zunstable-options --timings=html"
STD_FLAGS = "--profile ${RUSTC_PROFILE} --features std"
TEST_FLAGS = { value = "", condition = { env_not_set = ["TEST_FLAGS"] } }
COV_FLAGS = { value = "--workspace --out html --out xml --exclude-files **/tests/* --exclude-files **/benches/* --exclude uefi_test_macro", condition = { env_not_set = ["COV_FLAGS"] } }

[tasks.individual-package-targets]
script_runner = "@duckscript"
script = '''
args = get_env CARGO_MAKE_TASK_ARGS

if is_empty ${args}
  exit
end

1 = array ""
2 = split ${args} ,
3 = array_concat ${1} ${2}
joined_args = array_join ${3} " -p "
release ${1}
release ${2}
release ${3}

joined_args = trim ${joined_args}
set_env INDIVIDUAL_PACKAGE_TARGETS ${joined_args}
release ${joined_args}
'''

[tasks.build-bin]
description = """Builds the standard library DXE core.

Customizations:
    -p [development|release]: Builds in debug or release. Default: development

Example:
    `cargo make build-bin`
    `cargo make -p release build-bin`
"""
clear = true
command = "cargo"
args = ["build", "@@split(STD_FLAGS, )", "--example", "dxe_core_std"]

[tasks.check_no_std]
description = "Checks rust code for no_std build errors with results."
private = true
command = "cargo"
args = ["check", "--target", "x86_64-unknown-uefi", "@@split(NO_STD_FLAGS, )", "@@split(CARGO_MAKE_TASK_ARGS, )"]

[tasks.check_std]
description = "Checks rust code for std build errors with results."
private = true
command = "cargo"
args = ["check", "@@split(STD_FLAGS, )", "@@split(CARGO_MAKE_TASK_ARGS, )"]

[tasks.check]
description = "Checks rust code for errors. Example `cargo make check`"
clear = true
run_task = [{ name = ["check_no_std", "check_std"], parallel = true }]

[tasks.test]
description = "Builds all rust tests in the workspace. Example `cargo make test`"
clear = true
command = "cargo"
args = ["test", "@@split(INDIVIDUAL_PACKAGE_TARGETS, )", "@@split(TEST_FLAGS, )"]
dependencies = ["individual-package-targets"]

[tasks.coverage]
description = "Build and run all tests and calculate coverage."
install_crate = false
clear = true
command = "cargo"
args = ["tarpaulin", "@@split(COV_FLAGS, )", "--output-dir", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target"]
dependencies = ["individual-package-targets"]

[tasks.coverage-filter]
description = "Generates the coverage filter to ignore coverage data for other packages."
private = true
script_runner = "@duckscript"
script = '''
package = get_env PACKAGE
members =  get_env CARGO_MAKE_CRATE_WORKSPACE_MEMBERS

1 = split ${members} ,

2 = array
for member in ${1}
  if not contains ${member} ${package}
    t = concat "--exclude-files " ${member} /*
    array_push ${2} ${t}
    release ${t}
  end
end

joined_args = trim ${2}
joined = array_join ${joined_args} " "

set_env PACKAGE_COVERAGE_FILTER ${joined}
release ${1}
release ${2}
release ${joined_args}
release ${joined}
'''

[tasks.coverage-fail-package]
private = true
install_crate = false
description = """Generates Code coverage for $(PACKAGE) and fails the build if coverage is below 80%."""
dependencies = ["coverage-filter"]
command = "cargo"
args = ["tarpaulin", "-p", "${PACKAGE}", "--fail-under", "80", "--exclude-files", "@@split(PACKAGE_COVERAGE_FILTER, )", "@@split(COV_FLAGS, )", "--output-dir", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target"]

[tasks.coverage-fail]
description = """Runs coverage on one or all packages and fails if coverage is below 80%.

Examples:
    `cargo make coverage-fail`
    `cargo make coverage-fail dxe_core`
"""
script_runner = "@duckscript"
script = '''
1 = get_env CARGO_MAKE_CRATE_WORKSPACE_MEMBERS
2 = split ${1} ,
3 = get_env CARGO_MAKE_TASK_ARGS

if not is_empty ${3}
    set_env PACKAGE ${3}
    cm_run_task coverage-fail-package
else
    for member in ${2}
        4 = split ${member} /
        5 = array_pop ${4}
        set_env PACKAGE ${5}
        cm_run_task coverage-fail-package
        release ${4}
        release ${5}
    end
endif

release ${1}
release ${2}
release ${3}
'''

[tasks.patch]
private = true
script_runner = "@duckscript"
script = '''
1 = get_env CARGO_MAKE_TASK_ARGS
needs_patch = not is_empty ${1}
patch_str = concat "\n[patch.patina-fw]"

if ${needs_patch}
    2 = split ${1} ;
    for repo in ${2}
        echo "Processing repo: ${repo}"
        if not is_path_exists ${repo}/Cargo.toml
            echo "Path ${repo}/Cargo.toml does not exist."
            exit 1
        end

        output = exec cargo metadata --format-version 1 --no-deps --manifest-path ${repo}/Cargo.toml
        if not eq ${output.code} 0
            echo "Error running cargo metadata on ${repo}"
            exit 1
        end

        metadata = json_parse --collection ${output.stdout}
        packages = map_get ${metadata} packages

        for package in ${packages}
            name = map_get ${package} name
            path = map_get ${package} id

            path = replace ${path} "path+file:///" ""
            temp = split ${path} "#"
            path = array_get ${temp} 0

            patch_str = concat ${patch_str} \n${name} = { path = \"${path}\"}
            release ${name}
            release ${path}
            release ${temp}
        end

        release ${packages}
        release ${metadata}
        release ${output}
    end
end

if ${needs_patch}
    # Create a backup to revert to
    cp Cargo.toml Cargo.toml.bak

    # Patch the Cargo.toml file
    appendfile Cargo.toml ${patch_str}
end

# Execute the actual cargo command
exit_code = exec --get-exit-code cargo make build-efi

if ${needs_patch}
    # Revert the Cargo.toml file to the original state
    mv Cargo.toml.bak Cargo.toml
end

exit #{exit_code}
'''

[tasks.build-efi]
command = "cargo"
args = ["build", "--bin", "${CARGO_BIN_NAME}", "--target", "${CARGO_BIN_TARGET}", "--features", "${CARGO_BIN_FEATURES}", "@@split(NO_STD_FLAGS, )"]

[tasks.build-efi-x64]
private = true
env = { CARGO_BIN_TARGET = "x86_64-unknown-uefi", CARGO_BIN_FEATURES = "x64" }
run_task = "patch"

[tasks.build-efi-aarch64]
private = true
env = { CARGO_BIN_TARGET = "aarch64-unknown-uefi", CARGO_BIN_FEATURES = "aarch64" }
run_task = "patch"

[tasks.q35]
description = """Builds the DEBUG Q35 UEFI firmware."""
env = { CARGO_BIN_NAME = "qemu_q35_dxe_core", "RUSTC_PROFILE" = "dev" }
run_task = "build-efi-x64"

[tasks.q35-release]
description = """Builds the RELEASE Q35 UEFI firmware."""
env = { CARGO_BIN_NAME = "qemu_q35_dxe_core", "RUSTC_PROFILE" = "release" }
run_task = "build-efi-x64"

[tasks.sbsa]
description = """Builds the DEBUG SBSA UEFI firmware."""
env = { CARGO_BIN_NAME = "qemu_sbsa_dxe_core", "RUSTC_PROFILE" = "dev" }
run_task = "build-efi-aarch64"

[tasks.sbsa-release]
description = """Builds the RELEASE SBSA UEFI firmware."""
env = { CARGO_BIN_NAME = "qemu_sbsa_dxe_core", "RUSTC_PROFILE" = "release" }
run_task = "build-efi-aarch64"

[tasks.doc]
description = "Builds all rust documentation in the workspace. Example `cargo make doc`"
env = { RUSTDOCFLAGS = "-D warnings"}
command = "cargo"
args = ["doc", "@@split(INDIVIDUAL_PACKAGE_TARGETS, )", "--features", "doc", "--open"]

[tasks.clippy]
description = "Run cargo clippy."
clear = true
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]

[tasks.fmt]
description = "Run cargo format."
clear = true
command = "cargo"
args = ["fmt", "--all"]

[tasks.cspell]
description = "Run cspell for spell checking." # npm install -g cspell@latest
script = "cspell --quiet  --no-progress --no-summary  --dot --gitignore -e \"{.git/**,.github/**,.vscode/**}\" ."

[tasks.deny]
description = "Run cargo deny."
install_crate = false
clear = true
command = "cargo"
args = ["deny", "check"]

[tasks.all]
description = "Run all tasks for PR readiness."
dependencies = [
    "deny",
    "clippy",
    "cspell",
    "q35",
    "sbsa",
    "q35-release",
    "sbsa-release",
    "test",
    "coverage",
    "fmt",
    "doc",
]
