# @file patina-qemu-pr-validation-post.yml
#
# A workflow that runs after Patina QEMU PR Validation completes and delegates
# post-processing to a patina-devops workflow that will ultimately assess the
# validation results and report them back to the PR.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0
##
name: Patina QEMU PR Validation Post

on:
  workflow_run:
    workflows: ["Patina QEMU PR Validation"]
    types: ["completed"]

permissions:
  contents: read
  actions: read

jobs:
  post-process:
    uses: OpenDevicePartnership/patina-devops/.github/workflows/PatinaQemuPrValidationPost.yml@patina_e2e_plat_validation
    with:
      conclusion: ${{ github.event.workflow_run.conclusion }}
      head-sha: ${{ github.event.workflow_run.head_sha }}
      triggering-run-id: ${{ fromJSON(github.event.workflow_run.id) }}
    secrets: inherit
